import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BarChart3,BookOpen,CheckCircle2,ChevronRight,Code2,Flame,LayoutDashboard,LogIn,LogOut,Menu,Plus,Search,Settings,Sun,Moon,Target,TrendingUp,UserPlus,X,Github} from 'lucide-react';
import {createUserWithEmailAndPassword,onAuthStateChanged,sendPasswordResetEmail,signInWithEmailAndPassword,signInWithPopup,signOut,updateProfile,GoogleAuthProvider,GithubAuthProvider} from 'firebase/auth';
import {doc,getDoc,setDoc} from 'firebase/firestore';
import {auth,db} from './firebase';
import './styles.css';

const topics=[['Basics',32],['Sorting',25],['Arrays',40],['Binary Search',32],['Strings',15],['Linked List',31],['Recursion',25],['Bit Manipulation',18],['Stack & Queue',30],['Sliding Window',12],['Heaps',17],['Greedy',17],['Binary Trees',35],['BST',18],['Graphs',51],['Dynamic Programming',56],['Tries',7]];
const initialProblems=[
{id:1,title:'Two Sum',topic:'Arrays',difficulty:'Easy',status:'Solved',source:'LeetCode'},
{id:2,title:'Best Time to Buy and Sell Stock',topic:'Arrays',difficulty:'Easy',status:'Solved',source:'LeetCode'},
{id:3,title:'Maximum Subarray',topic:'Arrays',difficulty:'Medium',status:'Solved',source:'LeetCode'},
{id:4,title:'Binary Search',topic:'Binary Search',difficulty:'Easy',status:'Solved',source:'LeetCode'},
{id:5,title:'Search Insert Position',topic:'Binary Search',difficulty:'Easy',status:'Review',source:'LeetCode'},
{id:6,title:'Container With Most Water',topic:'Arrays',difficulty:'Medium',status:'Solved',source:'LeetCode'},
{id:7,title:'Product of Array Except Self',topic:'Arrays',difficulty:'Medium',status:'Attempted',source:'LeetCode'},
{id:8,title:'Valid Parentheses',topic:'Stack & Queue',difficulty:'Easy',status:'Not started',source:'LeetCode'},
{id:9,title:'Reverse Linked List',topic:'Linked List',difficulty:'Easy',status:'Not started',source:'LeetCode'}];
const statuses=['Not started','Attempted','Review','Solved'];
const today=()=>new Date().toISOString().slice(0,10);
const daysAgo=n=>{const d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)};
const initials=v=>(v||'CV').split(/[ @._-]+/).filter(Boolean).slice(0,2).map(x=>x[0].toUpperCase()).join('')||'CV';
const calcStreak=days=>{const set=new Set(days||[]);let s=0;for(let i=0;;i++){if(set.has(daysAgo(i)))s++;else break}return s};
const topicSolved=(items,t)=>items.filter(p=>p.topic===t&&p.status==='Solved').length;

function App(){
 const [user,setUser]=useState(null),[authMode,setAuthMode]=useState(null),[active,setActive]=useState('Dashboard'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[menu,setMenu]=useState(false),[toast,setToast]=useState(''),[settings,setSettings]=useState(false),[theme,setTheme]=useState(localStorage.getItem('codevault-theme')||'dark'),[items,setItems]=useState(initialProblems),[activity,setActivity]=useState([]);
 useEffect(()=>onAuthStateChanged(auth,async current=>{setUser(current);if(current){try{const snap=await getDoc(doc(db,'users',current.uid,'codevault','progress'));if(snap.exists()){const d=snap.data();if(Array.isArray(d.problems))setItems(d.problems);if(Array.isArray(d.activity))setActivity(d.activity)}}catch(e){console.error(e)}}else{const saved=localStorage.getItem('codevault-progress');if(saved){try{const d=JSON.parse(saved);setItems(d.problems||initialProblems);setActivity(d.activity||[])}catch{}}}}),[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('codevault-theme',theme)},[theme]);
 const notify=m=>{setToast(m);clearTimeout(window.__cvToast);window.__cvToast=setTimeout(()=>setToast(''),1800)};
 const persist=async(next,act)=>{const payload={problems:next,activity:act,updatedAt:new Date().toISOString()};try{if(user)await setDoc(doc(db,'users',user.uid,'codevault','progress'),payload,{merge:true});else localStorage.setItem('codevault-progress',JSON.stringify(payload))}catch(e){console.error(e);notify('Could not sync — check Firestore rules')}};
 const mark=(id,status)=>{const next=items.map(p=>p.id===id?{...p,status}:p);const act=status==='Solved'&&!activity.includes(today())?[...activity,today()]:activity;setItems(next);setActivity(act);persist(next,act);notify('Progress saved')};
 const logout=async()=>{await signOut(auth);notify('Signed out')};
 const done=items.filter(p=>p.status==='Solved').length,total=topics.reduce((a,x)=>a+x[1],0),streak=calcStreak(activity),visible=useMemo(()=>items.filter(p=>(filter==='All'||p.difficulty===filter)&&(p.title.toLowerCase().includes(query.toLowerCase())||p.topic.toLowerCase().includes(query.toLowerCase()))),[items,filter,query]);
 const nav=n=>{setActive(n);setMenu(false)};
 return <div className="app">
  <aside className={menu?'open':''}><div className="brand"><div className="brandmark"><Code2 size={20}/></div><span>CodeVault</span></div><nav>{[['Dashboard',LayoutDashboard],['A2Z Roadmap',BookOpen],['Problems',CheckCircle2],['Analytics',BarChart3]].map(([n,I])=><button className={active===n?'active':''} onClick={()=>nav(n)} key={n}><I size={18}/><span>{n}</span></button>)}</nav><div className="sideBottom"><div className="miniGoal"><div><span>Weekly goal</span><b>{Math.min(done,7)} / 7</b></div><div className="progress"><i style={{width:`${Math.min(done/7*100,100)}%`}}/></div><small>{done>=7?'Goal complete 🎉':`${Math.max(7-done,0)} more to hit your goal`}</small></div><div className="profile"><div className="avatar">{initials(user?.displayName||user?.email||'KA')}</div><div><b>{user?.displayName||user?.email?.split('@')[0]||'Guest'}</b><small>{user?'Synced to Firebase':'Local mode'}</small></div></div></div></aside>
  <main><header><button className="mobileMenu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="crumb"><span>CodeVault</span><ChevronRight size={15}/><b>{active}</b></div><div className="headerRight"><div className="streak"><Flame size={17}/><b>{streak}</b> day streak</div>{user?<><button className="iconBtn" onClick={()=>setSettings(true)}><Settings size={17}/></button><button className="userBtn" onClick={logout}><div className="avatar">{initials(user.displayName||user.email)}</div><LogOut size={14}/></button></>:<button className="loginTop" onClick={()=>setAuthMode('signin')}><LogIn size={15}/> Sign in</button>}</div></header>
  <section className="content">
   {active==='Dashboard'&&<><div className="hero"><div><p className="eyebrow">STRIVER A2Z • YOUR WORKSPACE</p><h1>Keep the streak.<br/><em>Master the patterns.</em></h1><p className="sub">Track every problem, build consistency, and sync your DSA journey across devices.</p><div className="heroActions">{!user&&<button className="primary" onClick={()=>setAuthMode('signup')}><UserPlus size={16}/> Create free account</button>}<button className="ghost" onClick={()=>nav('Problems')}>Open tracker <ChevronRight size={16}/></button></div></div><div className="heroOrb"><div className="orbInner"><Flame size={30}/><strong>{streak}</strong><span>DAY STREAK</span></div></div></div>
    <div className="stats"><Stat icon={CheckCircle2} label="Problems solved" value={done} meta={`of ${total} in A2Z`}/><Stat icon={Target} label="Today's target" value={`${Math.min(done,3)} / 3`} meta={done>=3?'Target complete':'Keep going'}/><Stat icon={TrendingUp} label="A2Z progress" value={`${Math.round(done/total*100)}%`} meta="17-step roadmap"/><Stat icon={Flame} label="Best streak" value={streak} meta="days"/></div>
    <div className="grid"><div className="panel roadmap"><div className="panelHead"><div><h2>Striver A2Z roadmap</h2><p>Follow the sheet one pattern at a time.</p></div><button className="ghost" onClick={()=>nav('A2Z Roadmap')}>View roadmap <ChevronRight size={16}/></button></div><div className="topicList">{topics.slice(0,8).map((t,i)=><Topic key={t[0]} index={i} topic={t} solved={topicSolved(items,t[0])}/>)}</div></div><div className="panel heat"><div className="panelHead"><div><h2>Consistency</h2><p>Last 12 weeks</p></div><b className="green">{activity.length} active days</b></div><div className="heatmap">{Array.from({length:84},(_,i)=>{const d=daysAgo(83-i);return <i key={i} className={activity.includes(d)?'l3':i%9===0?'l1':''}/>})}</div><div className="heatLegend"><span>Less</span>{['','l1','l2','l3'].map((x,i)=><i className={x} key={i}/>)}<span>More</span></div><div className="quote">“Consistency beats intensity.”<small>— Your reminder</small></div></div></div>
    <div className="panel recent"><div className="panelHead"><div><h2>Recent problems</h2><p>Your latest practice</p></div><button className="ghost" onClick={()=>nav('Problems')}>View all <ChevronRight size={16}/></button></div><ProblemTable data={items.slice(0,6)} onMark={mark}/></div></>}
   {active==='Problems'&&<><div className="pageTitle"><div><p className="eyebrow">YOUR PRACTICE LOG</p><h1>Problems</h1><p>Mark each problem as <b>Not started, Attempted, Review,</b> or <b>Solved.</b></p></div><button className="primary" onClick={()=>notify('Custom problem builder coming next')}><Plus size={17}/> Add problem</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search problems or topics..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filters">{['All','Easy','Medium','Hard'].map(x=><button className={filter===x?'selected':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="panel recent"><ProblemTable data={visible} onMark={mark}/></div></>}
   {active==='A2Z Roadmap'&&<><div className="pageTitle"><div><p className="eyebrow">STRIVER A2Z SHEET</p><h1>Your roadmap</h1><p>17 steps. Your progress. Your pace.</p></div><div className="roadProgress"><b>{Math.round(done/total*100)}%</b><span>complete</span></div></div><div className="roadGrid">{topics.map((t,i)=><div className="roadCard" key={t[0]}><div className="roadNo">STEP {String(i+1).padStart(2,'0')}</div><h3>{t[0]}</h3><p>{topicSolved(items,t[0])} of {t[1]} tracked as solved</p><div className="progress"><i style={{width:`${Math.min(topicSolved(items,t[0])/t[1]*100,100)}%`}}/></div><small>{Math.max(t[1]-topicSolved(items,t[0]),0)} remaining</small></div>)}</div></>}
   {active==='Analytics'&&<><div className="pageTitle"><div><p className="eyebrow">PERFORMANCE</p><h1>Analytics</h1><p>Understand your pace and sharpen weak areas.</p></div></div><div className="analyticsGrid"><div className="panel bigChart"><div className="panelHead"><div><h2>Problems solved</h2><p>Tracked in this account</p></div><b>{done}</b></div><div className="bars">{[2,4,3,6,4,7,5,8,6,10,8,12,9,14,11].map((v,i)=><div key={i}><i style={{height:`${v*7}px`}}/><small>{i%3===0?`${i+1}`:''}</small></div>)}</div></div><div className="panel"><div className="panelHead"><div><h2>Difficulty split</h2><p>Current tracker</p></div></div><div className="donut"><strong>{done}</strong><span>solved</span></div><div className="diffRows"><span><i className="dot easy"/>Easy <b>{items.filter(x=>x.status==='Solved'&&x.difficulty==='Easy').length}</b></span><span><i className="dot med"/>Medium <b>{items.filter(x=>x.status==='Solved'&&x.difficulty==='Medium').length}</b></span><span><i className="dot hard"/>Hard <b>{items.filter(x=>x.status==='Solved'&&x.difficulty==='Hard').length}</b></span></div></div></div></>}
  </section></main>
  {!user&&<button className="floatingAuth" onClick={()=>setAuthMode('signin')}><LogIn size={16}/> Sign in to sync</button>}
  {toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}</div>}
  {authMode&&<AuthModal mode={authMode} setMode={setAuthMode} close={()=>setAuthMode(null)} onDone={m=>{setAuthMode(null);notify(m)}}/>}
  {settings&&<SettingsModal theme={theme} setTheme={setTheme} close={()=>setSettings(false)} logout={logout} />}
 </div>;
}
function Topic({index,topic,solved}){return <div className="topic"><div className="topicNum">{String(index+1).padStart(2,'0')}</div><div className="topicInfo"><div><b>{topic[0]}</b><span>{solved} / {topic[1]}</span></div><div className="progress"><i style={{width:`${Math.min(solved/topic[1]*100,100)}%`}}/></div></div><ChevronRight size={16}/></div>}
function Stat({icon:Icon,label,value,meta}){return <div className="stat"><div className="statIcon"><Icon size={18}/></div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div>}
function ProblemTable({data,onMark}){return <div className="table">{data.length?data.map(p=><div className="row" key={p.id}><div className="check">{p.status==='Solved'?<CheckCircle2 size={19}/>:<span/>}</div><div className="pname"><b>{p.title}</b><small>{p.topic} • {p.source}</small></div><span className={`difficulty ${p.difficulty.toLowerCase()}`}>{p.difficulty}</span><select value={p.status} onChange={e=>onMark(p.id,e.target.value)} className={`statusSelect ${p.status.toLowerCase().replace(' ','-')}`}>{statuses.map(s=><option key={s}>{s}</option>)}</select><ChevronRight size={17} className="rowArrow"/></div>):<div className="empty">No problems match your search.</div>}</div>}
function AuthModal({mode,setMode,close,onDone}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{if(mode==='signup'){const c=await createUserWithEmailAndPassword(auth,email,password);if(name)await updateProfile(c.user,{displayName:name});onDone('Account created — progress can now sync across devices')}else{await signInWithEmailAndPassword(auth,email,password);onDone('Welcome back')}}catch(err){setError(firebaseMessage(err))}finally{setBusy(false)}};
 const popup=async provider=>{setBusy(true);setError('');try{await signInWithPopup(auth,provider);onDone(provider.providerId==='github.com'?'GitHub sign-in successful':'Google sign-in successful')}catch(err){setError(firebaseMessage(err))}finally{setBusy(false)}};
 const reset=async()=>{if(!email)return setError('Enter your email first.');try{await sendPasswordResetEmail(auth,email);setError('Password reset email sent.')}catch(err){setError(firebaseMessage(err))}};
 return <div className="modalBackdrop"><div className="authCard"><button className="close" onClick={close}><X/></button><div className="authLogo"><Code2 size={21}/></div><p className="eyebrow">CODEVAULT ACCOUNT</p><h2>{mode==='signup'?'Create your vault':'Welcome back'}</h2><p className="authSub">Save your Striver A2Z progress across devices.</p><form onSubmit={submit}>{mode==='signup'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/>}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" required/><input type="password" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (6+ characters)" required/><button disabled={busy} className="primary full">{busy?'Please wait...':mode==='signup'?'Create account':'Sign in'}</button></form><button disabled={busy} className="googleBtn" onClick={()=>popup(new GoogleAuthProvider())}>Continue with Google</button><button disabled={busy} className="googleBtn" onClick={()=>popup(new GithubAuthProvider())}><Github size={15} style={{verticalAlign:'-3px',marginRight:7}}/>Continue with GitHub</button>{mode==='signin'&&<button className="linkBtn" onClick={reset}>Forgot password?</button>}{error&&<div className="authError">{error}</div>}<div className="switchAuth">{mode==='signup'?'Already have an account?':'New to CodeVault?'} <button onClick={()=>{setError('');setMode(mode==='signup'?'signin':'signup')}}>{mode==='signup'?'Sign in':'Create one'}</button></div></div></div>}
function SettingsModal({theme,setTheme,close,logout}){return <div className="modalBackdrop"><div className="settingsCard"><button className="close" onClick={close}><X/></button><p className="eyebrow">WORKSPACE</p><h2>Settings</h2><div className="settingBlock"><label>Appearance</label><p>Choose how CodeVault looks on your device.</p><div className="themeChoices"><button className={theme==='dark'?'chosen':''} onClick={()=>setTheme('dark')}><Moon size={15}/>Dark</button><button className={theme==='light'?'chosen':''} onClick={()=>setTheme('light')}><Sun size={15}/>Light</button></div></div><div className="settingBlock"><button className="primary full" onClick={logout}><LogOut size={15}/> Sign out</button></div></div></div>}
function firebaseMessage(e){const map={'auth/invalid-credential':'Email or password is incorrect.','auth/email-already-in-use':'An account already exists with this email.','auth/weak-password':'Use a password with at least 6 characters.','auth/popup-closed-by-user':'The sign-in popup was closed.','auth/popup-blocked':'Your browser blocked the sign-in popup.','auth/unauthorized-domain':'Add the current Vercel domain to Firebase Authentication → Settings → Authorized domains.','auth/account-exists-with-different-credential':'An account already exists with another sign-in method.'};return map[e?.code]||`Authentication failed: ${e?.code||'unknown error'}`}

createRoot(document.getElementById('root')).render(<App/>);
