import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BarChart3,BookOpen,CheckCircle2,ChevronRight,Code2,Flame,LayoutDashboard,Menu,Plus,Search,Target,TrendingUp,X} from 'lucide-react';
import './styles.css';

const topics=[
 ['Basics',32,18],['Sorting',25,12],['Arrays',40,21],['Binary Search',32,14],['Strings',15,7],['Linked List',31,5],['Recursion',25,3],['Bit Manipulation',18,2],['Stack & Queue',30,1],['Sliding Window',12,0],['Heaps',17,0],['Greedy',17,0],['Binary Trees',35,0],['BST',18,0],['Graphs',51,0],['Dynamic Programming',56,0],['Tries',7,0]
];
const problems=[
 {id:1,title:'Two Sum',topic:'Arrays',difficulty:'Easy',status:'Solved',source:'LeetCode'},
 {id:2,title:'Best Time to Buy and Sell Stock',topic:'Arrays',difficulty:'Easy',status:'Solved',source:'LeetCode'},
 {id:3,title:'Maximum Subarray',topic:'Arrays',difficulty:'Medium',status:'Solved',source:'LeetCode'},
 {id:4,title:'Binary Search',topic:'Binary Search',difficulty:'Easy',status:'Solved',source:'LeetCode'},
 {id:5,title:'Search Insert Position',topic:'Binary Search',difficulty:'Easy',status:'Review',source:'LeetCode'},
 {id:6,title:'Container With Most Water',topic:'Arrays',difficulty:'Medium',status:'Solved',source:'LeetCode'},
 {id:7,title:'Product of Array Except Self',topic:'Arrays',difficulty:'Medium',status:'Attempted',source:'LeetCode'},
 {id:8,title:'Valid Parentheses',topic:'Stack & Queue',difficulty:'Easy',status:'Not started',source:'LeetCode'},
 {id:9,title:'Reverse Linked List',topic:'Linked List',difficulty:'Easy',status:'Not started',source:'LeetCode'},
];
function App(){
 const [active,setActive]=useState('Dashboard'); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All'); const [menu,setMenu]=useState(false); const [toast,setToast]=useState('');
 const [items,setItems]=useState(problems);
 const done=items.filter(x=>x.status==='Solved').length; const total=topics.reduce((a,x)=>a+x[1],0); const solved=topics.reduce((a,x)=>a+x[2],0);
 const visible=useMemo(()=>items.filter(p=>(filter==='All'||p.difficulty===filter)&&(p.title.toLowerCase().includes(query.toLowerCase())||p.topic.toLowerCase().includes(query.toLowerCase()))),[items,filter,query]);
 const mark=(id)=>{setItems(items.map(p=>p.id===id?{...p,status:p.status==='Solved'?'Not started':'Solved'}:p));setToast('Progress updated');setTimeout(()=>setToast(''),1500)};
 return <div className="app">
  <aside className={menu?'open':''}><div className="brand"><div className="brandmark"><Code2 size={20}/></div><span>CodeVault</span></div><nav>{[['Dashboard',LayoutDashboard],['A2Z Roadmap',BookOpen],['Problems',CheckCircle2],['Analytics',BarChart3]].map(([n,I])=><button className={active===n?'active':''} onClick={()=>{setActive(n);setMenu(false)}} key={n}><I size={18}/><span>{n}</span></button>)}</nav><div className="sideBottom"><div className="miniGoal"><div><span>Weekly goal</span><b>4 / 7</b></div><div className="progress"><i style={{width:'57%'}}/></div><small>3 more to stay on track</small></div><div className="profile"><div className="avatar">KA</div><div><b>Kaif Ali</b><small>DSA Journey</small></div></div></div></aside>
  <main><header><button className="mobileMenu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="crumb"><span>CodeVault</span><ChevronRight size={15}/><b>{active}</b></div><div className="headerRight"><div className="streak"><Flame size={17}/> <b>7</b> day streak</div><div className="avatar">KA</div></div></header>
   <section className="content">
    {active==='Dashboard'&&<><div className="hero"><div><p className="eyebrow">STRIVER A2Z • YOUR WORKSPACE</p><h1>Keep the streak.<br/><em>Master the patterns.</em></h1><p className="sub">Track every problem, build consistency, and see exactly how far you've come.</p></div><div className="heroOrb"><div className="orbInner"><Flame size={30}/><strong>7</strong><span>DAY STREAK</span></div></div></div>
    <div className="stats"><Stat icon={CheckCircle2} label="Problems solved" value={solved} meta={`of ${total} in A2Z`}/><Stat icon={Target} label="Today's target" value="2 / 3" meta="1 problem left"/><Stat icon={TrendingUp} label="A2Z progress" value={`${Math.round(solved/total*100)}%`} meta="Keep going"/><Stat icon={Flame} label="Best streak" value="14" meta="days"/></div>
    <div className="grid"><div className="panel roadmap"><div className="panelHead"><div><h2>Striver A2Z roadmap</h2><p>Follow the sheet, one pattern at a time.</p></div><button className="ghost" onClick={()=>setActive('A2Z Roadmap')}>View roadmap <ChevronRight size={16}/></button></div><div className="topicList">{topics.slice(0,8).map((t,i)=><div className="topic" key={t[0]}><div className="topicNum">{String(i+1).padStart(2,'0')}</div><div className="topicInfo"><div><b>{t[0]}</b><span>{t[2]} / {t[1]}</span></div><div className="progress"><i style={{width:`${t[1]?t[2]/t[1]*100:0}%`}}/></div></div><ChevronRight size={16}/></div>)}</div></div>
     <div className="panel heat"><div className="panelHead"><div><h2>Consistency</h2><p>Last 12 weeks</p></div><b className="green">72% active</b></div><div className="heatmap">{Array.from({length:84},(_,i)=><i key={i} className={i%13===0?'l3':i%7===0?'l2':i%4===0?'l1':''}/>)}</div><div className="heatLegend"><span>Less</span>{['','l1','l2','l3'].map((x,i)=><i className={x} key={i}/>)}<span>More</span></div><div className="quote">“Consistency beats intensity.”<small>— Your reminder</small></div></div></div>
    <div className="panel recent"><div className="panelHead"><div><h2>Recent problems</h2><p>Your latest practice</p></div><button className="ghost" onClick={()=>setActive('Problems')}>View all <ChevronRight size={16}/></button></div><ProblemTable data={items.slice(0,5)} onMark={mark}/></div></>}
    {active==='Problems'&&<><div className="pageTitle"><div><p className="eyebrow">YOUR PRACTICE LOG</p><h1>Problems</h1><p>Every problem you solve becomes part of your DSA story.</p></div><button className="primary" onClick={()=>setToast('Add problem flow coming next') }><Plus size={17}/> Add problem</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search problems or topics..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filters">{['All','Easy','Medium','Hard'].map(x=><button className={filter===x?'selected':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="panel recent"><ProblemTable data={visible} onMark={mark}/></div></>}
    {active==='A2Z Roadmap'&&<><div className="pageTitle"><div><p className="eyebrow">STRIVER A2Z SHEET</p><h1>Your roadmap</h1><p>17 steps. One system. No guesswork.</p></div><div className="roadProgress"><b>{Math.round(solved/total*100)}%</b><span>complete</span></div></div><div className="roadGrid">{topics.map((t,i)=><div className="roadCard" key={t[0]}><div className="roadNo">STEP {String(i+1).padStart(2,'0')}</div><h3>{t[0]}</h3><p>{t[2]} of {t[1]} problems solved</p><div className="progress"><i style={{width:`${t[1]?t[2]/t[1]*100:0}%`}}/></div><small>{t[1]-t[2]} remaining</small></div>)}</div></>}
    {active==='Analytics'&&<><div className="pageTitle"><div><p className="eyebrow">PERFORMANCE</p><h1>Analytics</h1><p>Understand your pace and sharpen weak areas.</p></div></div><div className="analyticsGrid"><div className="panel bigChart"><div className="panelHead"><div><h2>Problems solved</h2><p>Last 30 days</p></div><b>18</b></div><div className="bars">{[3,5,2,6,4,8,5,7,10,8,12,9,14,11,16].map((v,i)=><div key={i}><i style={{height:`${v*7}px`}}/><small>{i%3===0?`${i+1}`:''}</small></div>)}</div></div><div className="panel"><div className="panelHead"><div><h2>Difficulty split</h2><p>Across solved problems</p></div></div><div className="donut"><strong>{solved}</strong><span>solved</span></div><div className="diffRows"><span><i className="dot easy"/>Easy <b>12</b></span><span><i className="dot med"/>Medium <b>6</b></span><span><i className="dot hard"/>Hard <b>0</b></span></div></div></div></>}
   </section>
  </main>{toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}</div>}
 </div>
}
function Stat({icon:Icon,label,value,meta}){return <div className="stat"><div className="statIcon"><Icon size={18}/></div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div>}
function ProblemTable({data,onMark}){return <div className="table">{data.length?data.map(p=><div className="row" key={p.id}><div className="check" onClick={()=>onMark(p.id)}>{p.status==='Solved'?<CheckCircle2 size={19}/>:<span/>}</div><div className="pname"><b>{p.title}</b><small>{p.topic}</small></div><span className={`difficulty ${p.difficulty.toLowerCase()}`}>{p.difficulty}</span><span className={`status ${p.status.toLowerCase().replace(' ','-')}`}>{p.status}</span><button className="rowArrow" onClick={()=>onMark(p.id)}><ChevronRight size={17}/></button></div>):<div className="empty">No problems match your search.</div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
