import React,{useEffect,useMemo,useState} from 'react';
import {BarChart3,BookOpen,CheckCircle2,ChevronDown,ChevronRight,Code2,ExternalLink,Flame,Github,LayoutDashboard,Library,LogIn,LogOut,Menu,Moon,Search,Settings,Sun,Target,TrendingUp,UserPlus,X,Youtube} from 'lucide-react';
import {createUserWithEmailAndPassword,onAuthStateChanged,sendPasswordResetEmail,signInWithEmailAndPassword,signInWithPopup,signOut,updateProfile,GoogleAuthProvider,GithubAuthProvider} from 'firebase/auth';
import {doc,getDoc,setDoc} from 'firebase/firestore';
import {auth,db} from './firebase';
import './styles.css';

const TUF_URL='https://takeuforward.org/dsa/strivers-a2z-sheet-learn-dsa-a-to-z';
const statuses=['Not started','Attempted','Review','Solved'];
const fallback=[
{id:1,title:'Two Sum',topic:'Arrays',difficulty:'Easy',questionUrl:'https://leetcode.com/problems/two-sum/',materialUrl:'',source:'LeetCode'},
{id:2,title:'Best Time to Buy and Sell Stock',topic:'Arrays',difficulty:'Easy',questionUrl:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',materialUrl:'',source:'LeetCode'},
{id:3,title:'Maximum Subarray',topic:'Arrays',difficulty:'Medium',questionUrl:'https://leetcode.com/problems/maximum-subarray/',materialUrl:'',source:'LeetCode'},
{id:4,title:'Container With Most Water',topic:'Arrays',difficulty:'Medium',questionUrl:'https://leetcode.com/problems/container-with-most-water/',materialUrl:'',source:'LeetCode'},
{id:5,title:'Product of Array Except Self',topic:'Arrays',difficulty:'Medium',questionUrl:'https://leetcode.com/problems/product-of-array-except-self/',materialUrl:'',source:'LeetCode'},
{id:6,title:'Binary Search',topic:'Binary Search',difficulty:'Easy',questionUrl:'https://leetcode.com/problems/binary-search/',materialUrl:'',source:'LeetCode'},
{id:7,title:'Search Insert Position',topic:'Binary Search',difficulty:'Easy',questionUrl:'https://leetcode.com/problems/search-insert-position/',materialUrl:'',source:'LeetCode'},
{id:8,title:'Valid Parentheses',topic:'Stack / Queues',difficulty:'Easy',questionUrl:'https://leetcode.com/problems/valid-parentheses/',materialUrl:'',source:'LeetCode'},
{id:9,title:'Reverse Linked List',topic:'Linked List',difficulty:'Easy',questionUrl:'https://leetcode.com/problems/reverse-linked-list/',materialUrl:'',source:'LeetCode'},
{id:10,title:'Palindrome Number',topic:'Learn the basics',difficulty:'Easy',questionUrl:'https://leetcode.com/problems/palindrome-number/',materialUrl:'',source:'LeetCode'},
{id:11,title:'Fibonacci Number',topic:'Learn the basics',difficulty:'Easy',questionUrl:'https://leetcode.com/problems/fibonacci-number/',materialUrl:'',source:'LeetCode'}];
const today=()=>new Date().toISOString().slice(0,10);
const daysAgo=n=>{const d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)};
const initials=v=>(v||'CV').split(/[ @._-]+/).filter(Boolean).slice(0,2).map(x=>x[0].toUpperCase()).join('')||'CV';
const calcStreak=days=>{const s=new Set(days||[]);let n=0;while(s.has(daysAgo(n)))n++;return n};
const normalizeTopic=t=>{const v=(t||'').toLowerCase();if(v.includes('sorting'))return 'Sorting';if(v.includes('array'))return 'Arrays';if(v.includes('binary search'))return 'Binary Search';if(v.includes('string'))return 'Strings';if(v.includes('linked'))return 'Linked List';if(v.includes('recursion'))return 'Recursion';if(v.includes('bit'))return 'Bit Manipulation';if(v.includes('stack')||v.includes('queue'))return 'Stack / Queues';if(v.includes('sliding')||v.includes('two pointer'))return 'Sliding Window / Two Pointer';if(v.includes('heap'))return 'Heaps';if(v.includes('greedy'))return 'Greedy';if(v.includes('binary tree'))return 'Binary Trees';if(v.includes('bst'))return 'BST';if(v.includes('graph'))return 'Graphs';if(v.includes('dynamic programming'))return 'Dynamic Programming';if(v.includes('trie'))return 'Tries';if(v.includes('basic'))return 'Learn the basics';return t||'Other'};

function App(){
 const [user,setUser]=useState(null),[catalog,setCatalog]=useState(fallback),[states,setStates]=useState({}),[activity,setActivity]=useState([]),[active,setActive]=useState('Dashboard');
 const [query,setQuery]=useState(''),[topic,setTopic]=useState('All'),[difficulty,setDifficulty]=useState('All'),[status,setStatus]=useState('All'),[authMode,setAuthMode]=useState(null),[settings,setSettings]=useState(false),[theme,setTheme]=useState(localStorage.getItem('codevault-theme')||'dark'),[menu,setMenu]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>{fetch('/a2z-problems.json').then(r=>r.ok?r.json():Promise.reject()).then(d=>Array.isArray(d)&&d.length&&setCatalog(d)).catch(()=>{})},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('codevault-theme',theme)},[theme]);
 useEffect(()=>onAuthStateChanged(auth,async current=>{setUser(current);if(current){try{const snap=await getDoc(doc(db,'users',current.uid,'codevault','progress'));if(snap.exists()){const d=snap.data();setStates(d.states||{});setActivity(d.activity||[])}}catch{}}else{const s=localStorage.getItem('codevault-progress-v2');if(s)try{const d=JSON.parse(s);setStates(d.states||{});setActivity(d.activity||[])}catch{}}}),[]);
 const problems=useMemo(()=>catalog.map(p=>({...p,topic:normalizeTopic(p.topic),status:states[p.id]||'Not started'})),[catalog,states]);
 const topics=useMemo(()=>[...new Set(problems.map(p=>p.topic))].sort(),[problems]);
 const visible=useMemo(()=>problems.filter(p=>{const q=`${p.title} ${p.topic}`.toLowerCase();return(!query||q.includes(query.toLowerCase()))&&(topic==='All'||p.topic===topic)&&(difficulty==='All'||p.difficulty===difficulty)&&(status==='All'||p.status===status)}),[problems,query,topic,difficulty,status]);
 const solved=problems.filter(p=>p.status==='Solved').length,review=problems.filter(p=>p.status==='Review').length,streak=calcStreak(activity),total=problems.length;
 const notify=m=>{setToast(m);clearTimeout(window.__cvToast);window.__cvToast=setTimeout(()=>setToast(''),1800)};
 const persist=async(ns,na)=>{const payload={states:ns,activity:na,updatedAt:new Date().toISOString()};if(user)await setDoc(doc(db,'users',user.uid,'codevault','progress'),payload,{merge:true});else localStorage.setItem('codevault-progress-v2',JSON.stringify(payload))};
 const mark=async(id,next)=>{const ns={...states,[id]:next};const na=next==='Solved'&&!activity.includes(today())?[...activity,today()]:activity;setStates(ns);setActivity(na);try{await persist(ns,na);notify(next==='Solved'?'Solved • streak updated':'Progress saved')}catch{notify('Saved locally; cloud sync failed')}};
 const nav=n=>{setActive(n);setMenu(false)}; const logout=async()=>{await signOut(auth);notify('Signed out')};
 return <div className="app">
  <aside className={menu?'open':''}><div className="brand"><div className="brandmark"><Code2 size={20}/></div><span>CodeVault</span></div><nav>{[['Dashboard',LayoutDashboard],['A2Z Roadmap',BookOpen],['Problems',CheckCircle2],['Resources',Library],['Analytics',BarChart3]].map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>nav(n)}><I size={18}/><span>{n}</span></button>)}</nav><div className="sideBottom"><div className="miniGoal"><div><span>Weekly goal</span><b>{Math.min(solved,7)} / 7</b></div><div className="progress"><i style={{width:`${Math.min(solved/7*100,100)}%`}}/></div><small>{solved>=7?'Goal complete 🎉':`${Math.max(7-solved,0)} more`}</small></div><div className="profile"><div className="avatar">{initials(user?.displayName||user?.email||'KA')}</div><div><b>{user?.displayName||user?.email?.split('@')[0]||'Guest'}</b><small>{user?'Firebase synced':'Local mode'}</small></div></div></div></aside>
  <main><header><button className="mobileMenu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="crumb"><b>CodeVault</b><ChevronRight size={15}/><span>{active}</span></div><div className="topSearch"><Search size={15}/><input value={query} onChange={e=>{setQuery(e.target.value);if(active!=='Problems')setActive('Problems')}} placeholder="Search A2Z problems…"/><kbd>⌘ K</kbd></div><div className="headerRight"><div className="streak"><Flame size={17}/><b>{streak}</b> day streak</div><button className="iconBtn" title="Toggle theme" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button>{user?<><button className="iconBtn" onClick={()=>setSettings(true)}><Settings size={17}/></button><button className="userBtn" onClick={logout}><div className="avatar">{initials(user.displayName||user.email)}</div><LogOut size={14}/></button></>:<button className="loginTop" onClick={()=>setAuthMode('signin')}><LogIn size={15}/> Sign in</button>}</div></header>
  <section className="content">
   {active==='Dashboard'&&<Dashboard solved={solved} total={total} review={review} streak={streak} topics={topics} problems={problems} onNavigate={nav}/>} 
   {active==='A2Z Roadmap'&&<Roadmap topics={topics} problems={problems} onOpen={t=>{setTopic(t);setActive('Problems')}}/>}
   {active==='Problems'&&<ProblemsView problems={problems} visible={visible} topics={topics} query={query} setQuery={setQuery} topic={topic} setTopic={setTopic} difficulty={difficulty} setDifficulty={setDifficulty} status={status} setStatus={setStatus} onMark={mark}/>} 
   {active==='Resources'&&<Resources/>}{active==='Analytics'&&<Analytics problems={problems} activity={activity}/>} 
  </section></main>
  {!user&&<button className="floatingAuth" onClick={()=>setAuthMode('signin')}><LogIn size={16}/> Sign in to sync</button>}{toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}</div>}{authMode&&<AuthModal mode={authMode} close={()=>setAuthMode(null)} onDone={notify}/>} {settings&&<SettingsModal theme={theme} setTheme={setTheme} close={()=>setSettings(false)} logout={logout} user={user}/>} 
 </div>}

function Dashboard({solved,total,review,streak,topics,problems,onNavigate}){return <><div className="hero"><div><p className="eyebrow">STRIVER A2Z • PERSONAL COMMAND CENTER</p><h1>Build the habit.<br/><em>Master the patterns.</em></h1><p className="sub">A2Z tracker with direct official questions, study material, progress and streaks.</p><div className="heroActions"><button className="primary" onClick={()=>onNavigate('Problems')}>Continue solving <ChevronRight size={16}/></button><a className="ghostLink" href={TUF_URL} target="_blank" rel="noreferrer">Official A2Z sheet <ExternalLink size={14}/></a></div></div><div className="heroOrb"><div className="orbInner"><Flame size={30}/><strong>{streak}</strong><span>DAY STREAK</span></div></div></div><div className="stats"><Stat icon={CheckCircle2} label="Problems solved" value={solved} meta={`of ${total}`}/><Stat icon={TrendingUp} label="A2Z progress" value={`${total?Math.round(solved/total*100):0}%`} meta="Full catalog"/><Stat icon={Target} label="Need revision" value={review} meta="review queue"/><Stat icon={Flame} label="Current streak" value={streak} meta="days"/></div><div className="grid"><div className="panel"><div className="panelHead"><div><h2>Topic progress</h2><p>Live catalog from the A2Z sheet.</p></div></div><div className="topicList">{topics.slice(0,10).map((t,i)=>{const l=problems.filter(p=>p.topic===t);return <Topic key={t} index={i} topic={t} solved={l.filter(p=>p.status==='Solved').length} total={l.length}/>})}</div></div><div className="panel"><div className="panelHead"><div><h2>Study links</h2><p>Open official learning material.</p></div></div><div className="quickLinks"><a href={TUF_URL} target="_blank" rel="noreferrer"><BookOpen size={15}/> Official A2Z sheet <ExternalLink size={13}/></a><a href="https://takeuforward.org/home" target="_blank" rel="noreferrer"><Library size={15}/> TakeUForward hub <ExternalLink size={13}/></a><a href="https://www.youtube.com/@takeUforward" target="_blank" rel="noreferrer"><Youtube size={15}/> TUF YouTube <ExternalLink size={13}/></a></div><div className="quote">“Consistency beats intensity.”<small>— CodeVault</small></div></div></div></>}
function Topic({index,topic,solved,total}){const pct=total?Math.round(solved/total*100):0;return <div className="topic"><div className="topicNum">{String(index+1).padStart(2,'0')}</div><div className="topicInfo"><div><b>{topic}</b><span>{solved} / {total}</span></div><div className="progress"><i style={{width:`${pct}%`}}/></div></div><span>{pct}%</span></div>}
function Stat({icon:Icon,label,value,meta}){return <div className="stat"><div className="statIcon"><Icon size={18}/></div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div>}
function Roadmap({topics,problems,onOpen}){return <><div className="pageTitle"><div><p className="eyebrow">STRIVER A2Z</p><h1>Roadmap</h1><p>Click a topic to open its full problem list.</p></div><a className="outlineLink" href={TUF_URL} target="_blank" rel="noreferrer">Official sheet <ExternalLink size={13}/></a></div><div className="roadGrid">{topics.map((t,i)=>{const l=problems.filter(p=>p.topic===t),s=l.filter(p=>p.status==='Solved').length,p=l.length?Math.round(s/l.length*100):0;return <button className="roadCard" key={t} onClick={()=>onOpen(t)}><div className="roadNo">STEP {String(i+1).padStart(2,'0')}</div><h3>{t}</h3><p>{s} solved • {l.length} total</p><div className="progress"><i style={{width:`${p}%`}}/></div><small>{p}% complete</small></button>})}</div></>}
function ProblemsView({problems,visible,topics,query,setQuery,topic,setTopic,difficulty,setDifficulty,status,setStatus,onMark}){return <><div className="pageTitle"><div><p className="eyebrow">A2Z PROBLEM DATABASE</p><h1>{problems.length} problems</h1><p>Each problem opens the official website directly. Materials open separately when available.</p></div><div className="catalogBadge"><b>{visible.length}</b><span>matches</span></div></div><div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search problem or topic..."/></div><Filter value={topic} options={['All',...topics]} onChange={setTopic}/><Filter value={difficulty} options={['All','Easy','Medium','Hard']} onChange={setDifficulty}/><Filter value={status} options={['All',...statuses]} onChange={setStatus}/></div><div className="panel problemPanel"><div className="catalogHead"><span>Problem</span><span>Difficulty</span><span>Status</span><span>Material</span><span>Question</span></div>{visible.slice(0,200).map(p=><div className="problemRow" key={p.id}><div className="problemTitle"><div className={`statusDot ${p.status.toLowerCase().replace(' ','-')}`}/><div><b>{p.title}</b><small>{p.topic} • {p.source}</small></div></div><span className={`difficulty ${p.difficulty.toLowerCase()}`}>{p.difficulty}</span><select className={`statusSelect ${p.status.toLowerCase().replace(' ','-')}`} value={p.status} onChange={e=>onMark(p.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select>{p.materialUrl?<a className="materialBtn" href={p.materialUrl} target="_blank" rel="noreferrer"><Youtube size={14}/> Watch</a>:<a className="materialBtn" href={TUF_URL} target="_blank" rel="noreferrer"><Library size={14}/> TUF</a>}{p.questionUrl?<a className="openBtn" href={p.questionUrl} target="_blank" rel="noreferrer">Open <ExternalLink size={13}/></a>:<a className="openBtn" href={TUF_URL} target="_blank" rel="noreferrer">Sheet <ExternalLink size={13}/></a>}</div>)}{!visible.length&&<div className="empty">No matches found.</div>}</div></>}
function Filter({value,options,onChange}){return <label className="selectWrap"><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select><ChevronDown size={13}/></label>}
function Resources(){return <><div className="pageTitle"><div><p className="eyebrow">STUDY MATERIAL</p><h1>Resources</h1><p>Official and companion links for the A2Z journey.</p></div></div><div className="resourceGrid"><a className="resourceCard featured" href={TUF_URL} target="_blank" rel="noreferrer"><div className="resourceIcon"><BookOpen/></div><span>STRIVER A2Z</span><h3>Official A2Z sheet</h3><p>Open the live TakeUForward roadmap.</p><ExternalLink size={15}/></a><a className="resourceCard" href="https://takeuforward.org/home" target="_blank" rel="noreferrer"><div className="resourceIcon"><Library/></div><span>TUF</span><h3>TakeUForward learning hub</h3><p>Theory, articles and DSA material.</p><ExternalLink size={15}/></a><a className="resourceCard" href="https://www.youtube.com/@takeUforward" target="_blank" rel="noreferrer"><div className="resourceIcon"><Youtube/></div><span>VIDEO</span><h3>TUF YouTube</h3><p>Video explanations and playlists.</p><ExternalLink size={15}/></a></div></>}
function Analytics({problems,activity}){const solved=problems.filter(p=>p.status==='Solved').length;return <><div className="pageTitle"><div><p className="eyebrow">PERFORMANCE</p><h1>Analytics</h1><p>Track your progress through the A2Z catalog.</p></div></div><div className="analyticsGrid"><div className="panel bigChart"><div className="panelHead"><div><h2>Difficulty split</h2><p>{solved} solved</p></div><b>{activity.length} active days</b></div><div className="bars">{['Easy','Medium','Hard'].map(d=>{const n=problems.filter(p=>p.status==='Solved'&&p.difficulty===d).length;return <div key={d}><i style={{height:`${Math.max(n*18,8)}px`}}/><small>{d}</small><b>{n}</b></div>})}</div></div><div className="panel"><div className="panelHead"><div><h2>Overall completion</h2><p>Current A2Z catalog</p></div></div><div className="donut"><strong>{problems.length?Math.round(solved/problems.length*100):0}%</strong><span>complete</span></div></div></div></>}
function AuthModal({mode,close,onDone}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{if(mode==='signup'){const c=await createUserWithEmailAndPassword(auth,email,password);if(name)await updateProfile(c.user,{displayName:name});onDone('Account created')}else{await signInWithEmailAndPassword(auth,email,password);onDone('Welcome back')}close()}catch(err){setError(authMsg(err.code))}finally{setBusy(false)}};const popup=async provider=>{setBusy(true);setError('');try{await signInWithPopup(auth,provider);onDone('Signed in');close()}catch(err){setError(authMsg(err.code))}finally{setBusy(false)}};const forgot=async()=>{if(!email)return setError('Enter email first');try{await sendPasswordResetEmail(auth,email);onDone('Reset email sent')}catch(err){setError(authMsg(err.code))}};return <div className="modalBackdrop"><div className="authCard"><button className="close" onClick={close}><X/></button><div className="authLogo"><Code2 size={22}/></div><p className="eyebrow">CODEVAULT ACCOUNT</p><h2>{mode==='signup'?'Create your vault':'Welcome back'}</h2><p className="authSub">Save your A2Z progress across devices.</p><form onSubmit={submit}>{mode==='signup'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/>}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" required/><input type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (6+ characters)" required/><button className="primary full" disabled={busy}>{busy?'Working…':mode==='signup'?'Create account':'Sign in'}</button></form><button className="providerBtn" onClick={()=>popup(new GoogleAuthProvider())} disabled={busy}>Continue with Google</button><button className="providerBtn" onClick={()=>popup(new GithubAuthProvider())} disabled={busy}><Github size={15}/> Continue with GitHub</button>{mode==='signin'&&<button className="linkBtn" onClick={forgot}>Forgot password?</button>}{error&&<div className="authError">{error}</div>}<div className="switchAuth">{mode==='signup'?'Already have an account? ':'New to CodeVault? '}<button onClick={()=>{setError('');close();}}>{mode==='signup'?'Sign in':'Create one'}</button></div></div></div>}
function SettingsModal({theme,setTheme,close,logout,user}){return <div className="modalBackdrop"><div className="settingsCard"><button className="close" onClick={close}><X/></button><p className="eyebrow">WORKSPACE</p><h2>Settings</h2><div className="settingBlock"><label>Theme</label><div className="themeChoices"><button className={theme==='dark'?'chosen':''} onClick={()=>setTheme('dark')}><Moon size={14}/> Dark</button><button className={theme==='light'?'chosen':''} onClick={()=>setTheme('light')}><Sun size={14}/> Light</button></div></div><div className="settingBlock"><label>Account</label><p>{user?.email||'Guest'}<br/>Progress sync: Firebase Firestore</p></div><div className="settingBlock"><button className="logoutSetting" onClick={logout}><LogOut size={14}/> Sign out</button></div></div></div>}
function authMsg(code=''){const m={'auth/invalid-credential':'Email or password is incorrect.','auth/email-already-in-use':'An account already exists for this email.','auth/weak-password':'Use a stronger password.','auth/unauthorized-domain':'Add the Vercel domain to Firebase Authorized Domains.','auth/popup-closed-by-user':'Popup closed.','auth/popup-blocked':'Allow popups for CodeVault.'};return m[code]||'Something went wrong. Check Firebase Authentication settings.'}
createRoot(document.getElementById('root')).render(<App/>);
